name: ProfileChatter Build

# Triggers
on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'data/**'
      - 'assets/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'data/**'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Generate SVG
        run: node src/build-profile.js
      - name: Record timestamp
        id: ts
        run: echo "ts=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Update README timestamp
        run: |
          TS=${{ steps.ts.outputs.ts }}
          sed -i "s|profile-chat.svg?ts=[0-9]*|profile-chat.svg?ts=${TS}|g" README.md || true
          sed -i "s|profile-chat.svg)|profile-chat.svg?ts=${TS})|g" README.md || true

      - name: Detect changes
        id: diff
        run: |
          git diff --quiet || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Pull latest changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase --autostash origin main

      - name: Commit & push updated SVG
        if: steps.diff.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/profile-chat.svg README.md'
          message: "Auto-update profile chat SVG [skip ci] – ${{ steps.ts.outputs.ts }}"
          push: true

      - name: Done
        run: |
          if [[ "${{ steps.diff.outputs.changed }}" == "true" ]]; then
            echo "✅ SVG regenerated and committed."
          else
            echo "ℹ️ No changes – nothing to commit."
          fi