name: ProfileChatter Build

on:
  # Run every 6 hours to keep dynamic content updated
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

# Permissions required for the workflow to commit back to the repository
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          
      # Step 3: Install dependencies using the lock file for consistency
      - name: Install dependencies
        run: npm ci
        
      # Step 4: Run linter
      - name: Lint
        run: npm run lint
        
      # Step 5: Generate the SVG with dynamic data
      - name: Generate SVG
        id: generate
        run: node src/main.js
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          LOCATION_KEY: ${{ secrets.LOCATION_KEY }}
      
      # Step 6: Get current timestamp for cache busting
      - name: Get current timestamp
        id: timestamp
        run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT
      
      # Step 7: Update README timestamp
      - name: Update README timestamp
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.ts }}"
          sed -i "s|profile-chat.svg?ts=[0-9]*|profile-chat.svg?ts=$TIMESTAMP|g" README.md
          # Fallback if the timestamp parameter doesn't exist yet
          sed -i "s|profile-chat.svg)|profile-chat.svg?ts=$TIMESTAMP)|g" README.md
      
      # Step 8: Commit and push both SVG and README
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/profile-chat.svg README.md'
          message: 'Auto-update profile chat SVG [skip ci] - ${{ steps.timestamp.outputs.ts }}'
          author_name: 'ProfileChatter Bot'
          author_email: 'bot@profilechatter.example.com'
          push: true